/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package huff;

import ClasesParaHuffman.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.util.StringTokenizer;
import javax.swing.text.Caret;

/**
 *
 * @author Walther
 */
public class cmd extends javax.swing.JFrame {

    /**
     * Creates new form cmd
     */
    public cmd() {
        initComponents();
        taCMD.setBackground(Color.BLACK);
        taCMD.setCaretColor(Color.GREEN);
        taCMD.setForeground(Color.GREEN);
        jlPath.setText(home.getPath());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taCMD = new javax.swing.JTextArea();
        tfComando = new javax.swing.JTextField();
        jlPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taCMD.setEditable(false);
        taCMD.setColumns(20);
        taCMD.setRows(5);
        jScrollPane1.setViewportView(taCMD);

        tfComando.setBackground(new java.awt.Color(0, 0, 0));
        tfComando.setForeground(new java.awt.Color(0, 255, 0));
        tfComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfComandoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfComando, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfComando, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jlPath)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfComandoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComandoKeyPressed
        if (evt.getKeyChar() == '\n') {
            String comandoentero = tfComando.getText();
            StringTokenizer st = new StringTokenizer(comandoentero, " ");
            String comando = "", operacion = "";
            while(st.hasMoreElements()){
                if (comando.contentEquals("")) {
                    comando = (String)st.nextElement();
                }else{
                    operacion = (String)st.nextElement();
                }
            }
            if (comando.contentEquals("cd")) {
                if (operacion.contentEquals("..")) {
                    String pathHome = home.getPath();
                    System.out.println(pathHome);
                    if (!pathHome.contentEquals("C:\\")) {
                        int letrasPath = pathHome.length();
                        int temp = 0;
                        
                        for (int i = letrasPath-1; i >= 0; i--) {
                            char ch = pathHome.charAt(i);
                            if (ch == (char)92) {
                                temp = i;
                                break;
                            }
                        }
                        home = new File(pathHome.substring(0, temp+1));
                        taCMD.append("\n"+home.getPath()+"> "+comandoentero);
                        jlPath.setText(home.getPath());
                    }else{
                        taCMD.append("\n"+home.getPath()+"> "+comandoentero);
                        System.out.println(home.isDirectory());
                    }
                }else{
                    File newfile = new File(home.getPath()+"\\"+operacion);
                    if (newfile.isDirectory()) {
                        taCMD.append("\n"+home.getPath()+"> "+comandoentero);
                        home = new File(home.getPath()+"\\"+operacion);
                        jlPath.setText(home.getPath());
                    }else{
                        taCMD.append("\n"+home.getPath()+"> "+operacion+" no es un directorio.");
                    }
                }
            }else if (comando.contentEquals("ls")) {
                int cantidad = home.list().length;
                taCMD.append("\n"+home.getPath()+"> "+comandoentero);
                for (int i = 0; i < cantidad; i++) {
                    taCMD.append("\n"+home.list()[i]);
                }
                tfComando.setText("");
            }else if (comando.contentEquals("compress")) {
                listaNodosHuffman lis = new listaNodosHuffman();
                lis.textToList("hola mundo");
                lis.recorrer();
                tfComando.setText("");
            }else if (comando.contentEquals("decompress")) {
                
            }else if (comando.contentEquals("diff")) {
                
            }else if (comando.contentEquals("clear")) {
                taCMD.setText("");
                taCMD.append(home.getPath());
                tfComando.setText("");
            }
        }
    }//GEN-LAST:event_tfComandoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cmd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cmd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cmd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cmd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cmd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlPath;
    private javax.swing.JTextArea taCMD;
    private javax.swing.JTextField tfComando;
    // End of variables declaration//GEN-END:variables
    File home = new File("C:\\Users\\Walther");
    boolean primero = true;
}
